### ISSUE TITLE
automated testing and modernizing

### ISSUE THREAD

**Issue by zbeekman** [kmorel/UseLATEX#11]
I was just wondering if you had any interest in automating some testing, as well as modernizing the README. I’m just spitballing here, but if you like copy the text and add a check next to anything that appeals to you, with whatever comments.

If any of this appeals to you I could work up a pull request. Here are some ideas:
- [ ] Add a `CMakeLists.txt` file in the `tests` directory with `enable_testing()` and `add_test()` to drive each of the tests.
  - [ ] this could be included from the root `CMakeLists.txt` and would add a `tests` target to the `Makefile` to run the tests
  - [ ] chktex could be used (or lacheck or similar) to lint the UseLATEX.tex file to check for new errors being introduced
- [ ] Moving `README` to `README.md` for fancy formating etc.
  - [ ] a travis-ci badge can be added to the `README.md` to give users confidence that the software is stable and of high quality (or scare them away if the build is failing :smile: )
  - [ ] Badges highlighting the current stable release [![GitHub tag](https://img.shields.io/github/tag/kmorel/UseLATEX.svg?style=plastic)](https://github.com/kmorel/UseLATEX/releases) or the low open issue count [![GitHub tag](https://img.shields.io/github/issues-raw/kmorel/UseLATEX.svg?style=plastic)](https://github.com/kmorel/UseLATEX/issues)
- [ ] Use travis-ci to test commits and pull requests using the added tests above, as well as testing that the UseLATEX.tex document builds correctly.
- [ ] Use travis-ci to automate deployment:
  - [ ] travis-ci can create github releases whenever a new tag is created
  - [ ] travis-ci can run almost arbitrary commands to accomplish other deployment tasks, possibly scripting updating the UseLATEX entry and linked files on the CMake wiki, for example.
  - [ ] gh-pages could be used to archive and create a reference of compiled UseLATEX PDF manuals from previous tags, and travis-ci could auto deploy manuals for new tags, updates to master (development version) etc.

Some of this might be overkill, but automated testing and CI can be quite nice.

**Comment by kmorel** [comment]
I freely admit that the testing framework for UseLATEX.cmake is pretty lame. The whole thing is an afterthought added way late in the development. It could use some love.

Automated testing would be nice. However, one of the reasons I never implemented it is that it seems very hard to check to see if the test passed. Sure, it would be easy to determine that the LaTeX commands ran without an error code, and you could even easily check to make sure certain expected files were created. But how do you check to make sure that the built documents are created correctly? There are many ways in which LaTeX will run "correctly" but the document it creates is incomplete or wrong. So I'm not sure how much confidence automated tests would give. Do you know of a way to fix this problem?

As far as travis-ci, I admit that I know nothing about that project. It sounds good, but there has also been some interest in moving UseLATEX.cmake into the CMake build and distribution. That project has its own testing framework and the travis-ci code would be incompatible.

**Comment by zbeekman** [comment]
> I freely admit that the testing framework for UseLATEX.cmake is pretty lame. The whole thing is an afterthought added way late in the development. It could use some love.

Sure, now worries, a little is better than none :smile:

 > Automated testing would be nice. However, one of the reasons I never implemented it is that it seems very hard to check to see if the test passed. Sure, it would be easy to determine that the LaTeX commands ran without an error code, and you could even easily check to make sure certain expected files were created. But how do you check to make sure that the built documents are created correctly? There are many ways in which LaTeX will run "correctly" but the document it creates is incomplete or wrong. So I'm not sure how much confidence automated tests would give. Do you know of a way to fix this problem?

I’m no LaTeX expert, but here are some thoughts about a few additional possible tests:

 - search the .log file for signs of trouble. This is overwritten each time the latex command is run, and I usually add a search for undefined references
 - run chktex on your input LaTeX. This won’t ensure that UseLATEX.cmake works properly, but WILL ensure you minimize documentation errors and that the tex you pass to UseLATEX as tests is correct.
 - use tools like pdftotext to extract text from generated PDFs and compare against known correct output
 - use something like [diff-pdf](http://vslavik.github.io/diff-pdf/) to generate PDFs highlighting the differences between known valid output and current output—these would still have to be checked by hand at some point but might make this process easier.

 > As far as travis-ci, I admit that I know nothing about that project. It sounds good, but there has also been some interest in moving UseLATEX.cmake into the CMake build and distribution. That project has its own testing framework and the travis-ci code would be incompatible.

Well, nothing special would need to be added to any of the projects files, other than any additional tests you would like to add, as discussed above. (These can be added in the usual CMake way.) All that needs to happen is that a .travis.yml file is added to the repository root, and this contains build, test, and deployment instructions. Then head on over to travis-ci.org, log in with your github account and turn on travis-ci for this project (I typically also always check the only if .travis.yml is present box too.) The only non CMake stuff is that which is contained in the .travis.yml file.

**Comment by kmorel** [comment]
As the CMake project is consolidating their Wiki into their gitlab instance, I am moving this repository to their gitlab as well to simplify sharing files. As part of that process I am closing down old issues. I've tried to capture this issue in the new system at https://gitlab.kitware.com/kmorel/UseLATEX/issues/1 in case someone is inclined to work on it.
