### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [kmorel/UseLATEX#12]
Some parameters (like "[${dest}/${out_file}](https://github.com/kmorel/UseLATEX/blob/3264be4f0fd007f9b8a2a8325cb0a6bc687004ad/UseLATEX.cmake#L921)") are passed to CMake commands in your build script without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by kmorel** [comment]
Could you please provide an example where the current lack of quoting causes the build to fail?

**Comment by elfring** [comment]
Do you get any further ideas from [other bug reports](http://www.cmake.org/Bug/view.php?id=15076 "CMake does not support source/build trees with ';' in the path.") and corresponding update suggestions?

**Comment by kmorel** [comment]
As the CMake project is consolidating their Wiki into their gitlab instance, I am moving this repository to their gitlab as well to simplify sharing files. As part of that process I am closing down old issues. I've fixed issues with quoting parameters where I have encountered them. If there are further issues, please open up new issues on the new repository at https://gitlab.kitware.com/kmorel/UseLATEX.
