### ISSUE TITLE
Target name clash for tex files with identical names in subdirectories.

### ISSUE THREAD

**Issue by SimonHeybrock** [kmorel/UseLATEX#15]
Hi!

cmake fails when running `add_custom_target` (at various places in `UseLATEX.cmake`) in a setup as follows:

```
CMakeLists.txt
folderA/CMakeLists.txt
folderA/doc.tex
folderB/CMakeLists.txt
folderB/doc.tex
```
Here the top-level `CMakeLists.txt` adds both subdirectories. The `CMakeLists.txt` each contain `add_latex_document(doc.tex)`.

The problem is a clash between various automatically generated target names.

**Comment by kmorel** [comment]
Yes, I can see how that causes an issue, but I'm not sure the right way to fix it. After all, this is just the natural behavior of CMake. If instead of ```add_latex_document``` you were using, say, ```add_executable``` with the same name in two different folders, you would get the same behavior. The only real difference here is that with ```add_executable``` the generated file name (and target) is different than the filename whereas in LaTeX the generated file name is determined by the input filename.

How would you expect the behavior to change that makes sense?

**Comment by SimonHeybrock** [comment]
Hi,

Thanks for your reply. I certainly see your point.

An the other hand, there a two differences with `add_executable(mytarget mysource)`:
- It does not enforce naming changes of input files (I can have `mysource` in as many subfolders as I like).
- I can use `set_target_property(mytarget PROPERTIES OUTPUT_NAME myname)` to create output with the desired name.

I can see that this is not trivial to do with auto-generated target names. Maybe `add_latex_document` could be changed to (optionally) accept a target base-name, i.e., `add_latex_document(mytarget mysource.tex)`? Auto-generated names would then be `mytarget_pdf` instead of `mysource_pdf`, etc.

**Comment by kmorel** [comment]
@SimonHeybrock,

I just pushed a commit (SHA 82357b7dde50c4aad63704d2c813256ad8666ee2) that adds an option to ```add_latex_document``` called ```TARGET_NAME```. This option allows you to specify a target name different than the file name. So in your first example, you can prevent CMake errors by using ```add_latex_document(doc.tex TARGET_NAME docA)``` and ```add_latex_document(doc.tex TARGET_NAME docB)``` respectively in folderA and folderB.

Please try this out to see if it works for you. If so, I will push out a new version.

**Comment by SimonHeybrock** [comment]
Hi!
Thanks a lot, I can confirm that this works also for me. Thanks for your efforts! :)

**Comment by gruenich** [comment]
@kmorel Can you close this issue, as it is solved?

**Comment by kmorel** [comment]
Yup. Closed.
