### ISSUE TITLE
Try to use with the minted package (using pygmentize): LaTeX Error: FIle 'file.pyg' not found

### ISSUE THREAD

**Issue by tpabst** [kmorel/UseLATEX#16]
Hi,

I try to use UseLATEX with the 'minted' package. Minted use pygmentize (python-pygments on debian) to colorized code. 
LaTeX Error: FIle 'file.pyg' not found

Its working with the attached Makefile remamed makefile.txt

I can't joint it ! right are necessary

**Comment by kmorel** [comment]
I do not see any attachments to this issue. Something must have gone wrong there.

If I take a wild guess at what is going wrong, it is probably that CMake/UseLATEX copies all LaTeX input files to the build directory and runs commands from there. ```file.pyg``` is probably not copied from the source directory to the binary directory whereas your ```Makefile``` just runs LaTeX in place. The following CMake commands should copy ```file.pyg``` to the build directory and solve your problem.

```
latex_get_output_path(output_dir)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/file.pyg ${output_dir}/file.pyg)
```

You could modify this to use ```add_custom_command``` to do the copy during the build rather than the configuration, but this should work well enough.

**Comment by theMarix** [comment]
You should really use `COPYONLY` with `configure_file`. Otherwise it might try to expand variables in the copied file.

```
latex_get_output_path(output_dir)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/file.pyg ${output_dir}/file.pyg COPYONLY)
```

**Comment by kmorel** [comment]
Oops, yes. You are absolutely right. I should have put ```COPYDATA``` but forgot when typing it up. I corrected the comment above (so now people reading in the future will be confused).

**Comment by tpabst** [comment]
I must use `add_custom_command` because the file .pyg does not exist before the build. But where place this custom_command  in CMakeLists.txt ?

**Comment by kmorel** [comment]
Well, if the .pyg is created during the build, ideally you would have it be generated right in the output directory. Failing that, you could use ```add_custom_command``` to move it as follows. (Note, I'm freehanding this CMake code. I have not actually run it so there might be errors.)

```
latex_get_output_path(output_dir)
add_custom_command(
  OUTPUT ${output_dir}/file.pyg
  DEPENDS **input_directory**/file.pyg
  COMMAND ${CMAKE_COMMAND} -E copy **input_directory**/file.pyg ${output_dir}/file.pyg
  )
add_latex_document(
  ...
  DEPENDS ${output_dir}/file.pyg
  ...
  )
```

**Comment by kmorel** [comment]
As the CMake project is consolidating their Wiki into their gitlab instance, I am moving this repository to their gitlab as well to simplify sharing files. As part of that process I am closing down old issues. If you still need help resolving your issue, please open a new issue on the new repository at https://gitlab.kitware.com/kmorel/UseLATEX.
