### ISSUE TITLE
Unsucessful runs should swipe the output file!

### ISSUE THREAD

**Issue by dokempf** [kmorel/UseLATEX#19]
pdflatex - even when failing due to errors in the document - will always produce a pdf. The way how CMakes add_custom_command command thinks, this will be equivalent to successful generation of the decided pdf and upon future runs of 'make' the target will not be attempted to build (unless of course, some source changed).

I think this should be resolved by checking the return code of the pdflatex call and deleting any generated file in case it was not 0.

**Comment by kmorel** [comment]
This was fixed in UseLATEX.cmake version 2.4.4.
