### ISSUE TITLE
`LATEX_SMALL_IMAGES` failing

### ISSUE THREAD

**Issue by zbeekman** [kmorel/UseLATEX#26]
I have created an [ascii cast](https://asciinema.org/a/101757) demonstrating how to reproduce the problem. I am on MacOS Sierra, with the latest ImageMagick installed via [Homebrew](http://brew.sh). The conversion of png images seems to choke when resizing them:

[![uselatex-error](https://cloud.githubusercontent.com/assets/279612/22580851/d81df8d6-e9a9-11e6-9627-cf5c077b5fcc.gif)](https://asciinema.org/a/101757)

EDIT: BTW, clicking the GIF or asciicast link above will take you to a slower version... not sure why asciinema2gif creates such blazing fast gifs.

**Comment by zbeekman** [comment]
#11 could be helpful in ensuring all the features work... sorry I haven't had time to help out with that yet.

**Comment by zbeekman** [comment]
I did a git bisect for you and found the commit that introduced the breakage: e6358ec3494106b5e0035f64955cd801bad6e2c0

Here is the script I used:
```bash
#!/usr/bin/env bash
set -o pipefail
set -o errexit
set -o errtrace
set -o nounset

echo "Currently at top level, in $(PWD)"
echo "Changing to tests/ImageTypes"
cd tests/ImageTypes
echo "Currently in $(pwd)"
git status -sb
[[ -d "./build" ]] || mkdir build

cd build
rm -rf ./*
cmake .. -DLATEX_SMALL_IMAGES:BOOL=ON
make
status=$?
cd ../../..
exit $status
```

Here is what git reports:
```
e6358ec3494106b5e0035f64955cd801bad6e2c0 is the first bad commit
commit e6358ec3494106b5e0035f64955cd801bad6e2c0
Author: Kenneth Moreland <kmorel@sandia.gov>
Date:   Wed Sep 7 15:24:10 2016 -0600

    Support the use of magick instead of convert

    It looks like with the release of ImageMagick 7.0 that the name of the
    convert program has been renamed to magick. Most implementation have a
    link from convert to magick, but the windows install by default does
    not provide a convert program. To make sure it works everywhere, search
    for both programs (searching for magick first).

:100644 100644 803d7bae6ac615716b8653e2b10f20eced9168c0 0bc475160ef9ed3d03b519331b11dacea564a747 M	UseLATEX.cmake
bisect run success
```

Here is the asciinema replay of me finding the bug, in case you want to try to reproduce my findings:
[![asciicast](https://asciinema.org/a/101850.png)](https://asciinema.org/a/101850)

**Comment by zbeekman** [comment]
Hmmm perhaps this is an upstream bug with imagemagick, judging from the diff of https://github.com/kmorel/UseLATEX/commit/e6358ec3494106b5e0035f64955cd801bad6e2c0

**Comment by zbeekman** [comment]
I confirmed that as a work around, simply switching back to convert, say from `cmake-gui` or the command line with `-DIMAGEMAGICK_CONVERT:FILEPATH=/usr/local/bin/convert` makes the issue go away.

**Comment by kmorel** [comment]
@zbeekman Thanks for reporting this issue. It sounds like for the time being UseLATEX.cmake should prefer `convert` over `magick`. Can you check out pull request #27 and see if that more-or-less solves your problem?

Also, if this is a problem with ImageMagick, is there an open bug report in that project? Can you submit one if not?

**Comment by zbeekman** [comment]
> @zbeekman Thanks for reporting this issue. It sounds like for the time being UseLATEX.cmake should prefer convert over magick. Can you check out pull request #27 and see if that more-or-less solves your problem?

Looks like your fix should work, I'll test it in an hour or two when I have a moment.




> Also, if this is a problem with ImageMagick, is there an open bug report in that project? Can you submit one if not?

Not entirely sure what the deal with `magick` breakage is... I'll look for a bug tracker upstream and if I find one I'll report the bug there, then post a link here.

**Comment by zbeekman** [comment]
I can confirm that PR #27 fixes the issue. I have also reported the bug here: http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=31386#p142675

Please feel free to chime in with any additional insight.

**Comment by zbeekman** [comment]
OK, they responded, and it seems that you need to pass the input file as the very first argument in V7. This may apply to all the other programs as well.

**Comment by zbeekman** [comment]
Another useful link to read regarding the IM command line

**Comment by kmorel** [comment]
OK, I see now. In that case, this is something that we should be able to fix. I propose abandoning PR #27. I've instead created a new PR #29 that keeps `magick` as the default but fixes the order of arguments used. This seems to work for me. Can you verify that PR #29 resolves the issue for you?

**Comment by zbeekman** [comment]
yeah that fixes it for me too, thanks!

**Comment by kmorel** [comment]
Great. I'll merge the changes and close up this issue.
