### ISSUE TITLE
Question: list of figures, table of contents wraps w/ default target but not safe_pdf?

### ISSUE THREAD

**Issue by zbeekman** [kmorel/UseLATEX#30]
This might not be the appropriate place to ask this, but if I build the default target with `make` the my table of contents wrap correctly, and so does my list of figures. If I use the safe_pdf target `make document_safepdf` then it no longer wraps and I get overfull hboxes. Any thoughts on how to fix this?

Thanks,
-Z

**Comment by kmorel** [comment]
This might be a difference between using the `pdflatex` command (which is used by the default pdf target) and the `latex` command (which is used by the safe_pdf target).

Can you try building the dvi target? Do you get the same overfull behavior?

**Comment by zbeekman** [comment]
Yes I figured that was the case... and yes, making just the DVI creates the overfull hboxes and bad wrapping. I guess I need to figure out how to get latex to wrap like pdflatex

**Comment by kmorel** [comment]
You didn't specify, but if your lines are only going over the edge by a little bit, this might be a difference of tolerance for fussy/sloppy line filling. You might try the suggestion at this post: http://latex-community.org/forum/viewtopic.php?t=1268&start=20

**Comment by zbeekman** [comment]
Thanks for the tip, but no, the difference is that it is no longer wrapping, so the lines are going over by TONS. Well off the rendered/printed edge of the document. Because with pdflatex I get multiple lines for image captions and headings in the table of contents and list of figures, but latex just tries to put everything on one line without doing any wrapping.

**Comment by zbeekman** [comment]
Well it may be a good idea for me to use the short version optional arguments to \section and \caption anyway, so I guess I'll try doing that...
