### ISSUE TITLE
Problem when .bib file is not in current .tex directory

### ISSUE THREAD

**Issue by gnthibault** [kmorel/UseLATEX#31]
Hi all

First of all, thank you for developing this nice cmake command/scripts, it looks very handy.
However I am currently facing a problem, which may be related to me, misusing the add_latex_document() command.

I have the following directory tree:

root
--->CMakeLists.txt
--->biblio.bib
---[]Article1
------>CMakeLists.txt
------>Article1.tex
---[]Article2
------>CMakeLists.txt
------>Article2.tex

the root CMakeLists.txt only contains add_subdirectory for Article1 and Article2.
The two articles in directories Article1 and Article2 build fine if they have their local copy biblio1.bib and biblio2.bib files in their source directory.

However, if I want to factorize the biblioX.bib files into one single biblio.bib file, as presented in the directory tree structure above, I use an absolute path to the bib file as the BIBFILES option of the add_latex_document command, and I got the following error:

Scanning dependencies of target Article1_pdf
make[2]: *** No rule to make target '../output_directory/absolute_path_to_bib_file/biblio.bib', needed by '../doc/report1.pdf'.  Stop.

If I use a relative path for the BIBFILES option, the target builds fine, but my biblio.bib file is copied to the directory above my output directory, which is not what I want.

Is there a proper way to use a .bib file which is not in the same directory or in a subdirectory of a .tex file to be built ?

Thank you in advance for your help

**Comment by zbeekman** [comment]
Here is a potential work around: Have you tried creating a symbolic link to the master bib file from each of the article directories?

**Comment by gnthibault** [comment]
This does not work. Anyway, I am looking for the right way to use the add_latex_document() in this case than a workaround, because I already know how to build the two documents.

**Comment by kmorel** [comment]
LaTeX and its associated commands are not very flexible about the location of input files, and for that reason UseLATEX.cmake insists on having relative paths and copying all files to some location in the output directory. (There is more detail in the FAQ of the user's guide.) 

What you can do is change where UseLATEX.cmake copies files to. This can be controlled by a variable named LATEX_OUTPUT_PATH. You should be able to change that to make UseLATEX build your LaTeX files one directory deeper. But regardless, it is necessary to copy your .bib file to one directory below your .tex file.

**Comment by kmorel** [comment]
As the CMake project is consolidating their Wiki into their gitlab instance, I am moving this repository to their gitlab as well to simplify sharing files. As part of that process I am closing down old issues. If you still need help resolving your issue with bib files, please open a new issue on the new repository at https://gitlab.kitware.com/kmorel/UseLATEX.
