### ISSUE TITLE
Could NOT find UnixCommands

### ISSUE THREAD

**Issue by MathiasMagnus** [kmorel/UseLATEX#32]
Hi!

I am trying to demonstrate how CMake is suitable for end-to-end automation of an article creation process. (C/C++, invoking result, GnuPlot, LaTeX) I have hit a roadblock however. 

The elegance of CMake and LaTeX is that it is supposed to work cross-patform and I'm writing the demo on a Windows machine. However, if I try to compile a simple .tex file (+ .bib and an .eps to be inserted), UseLATEX.cmake complains about missing UnixCommands. Why? I downloaded MikTeX and that doesn't ship with any of these commands, so I guess pdflatex.exe does not depend on them. So what does? Is there a feature I'm using and I'm not aware of?

_Sidenote: apologies if my question is noobish. This kind of hassle is the reason I have never used LaTeX aside from the bare minimum I had to at university. I have already set aside my 'allure' of wanting to embed an .svg without the whirlwind of dependencies and settled for .eps. (SVG would be better, as it is a more Windows friendly format and I need not install GhostView or something similar to get the plots to display outside the document. Plus, SVG can be embedded into a Word document if need be.) Getting a document to display should not be rocket science (which seems far easier than getting LaTeX to compile)._

**Comment by kmorel** [comment]
I use UseLATEX regularly on my Windows machine, but I also have several Unix-like tools on my system, so it is possible there is a dependency I was not aware of. I tried to replicate your problem by (attempting to) remove my unix tool ports from my path and running CMake from the Windows command prompt. I got the following output:

```
C:\Users\kmorel\papers\UseLATEX\out>cmake -G Ninja ..
-- Found LATEX: C:/Program Files (x86)/MiKTeX 2.9/miktex/bin/latex.exe
-- Could NOT find UnixCommands (missing:  BASH CP GZIP MV RM TAR)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/kmorel/papers/UseLATEX/out
```

So I did get a message about UnixCommands not being found, but this was just a status message, not a warning or error. You should be able to still use the resulting build files. I looked through the code and I believe the unix commands are only used for managing SyncTex, which I doubt you are doing. You should be able to safely ignore this unless you get an actual error.

_Sidenote: My favorite way to insert vector graphics in a LaTeX document is to put it into a .pdf. The pdflatex command (which is the default for UseLATEX.cmake) will embed pdfs directly into the document._

**Comment by MathiasMagnus** [comment]
Thank you for the answer. Indeed, my initial compilation errors originated from missing packages, so as the dumbest solution I installed texlive-full in WSL and 'Select all installable" in MikTeX which solved my compilation issues on both Linux and Windows, as far as UseLATEX.cmake is concerned.

It was also my understanding that pdflatex.exe converts everything into pdfs and inserts those into the final document. SVG seemed like a natural choice, as it is XML based (which I am very fond of), it can be embedded into MS Word (my primary platform for producing documents), plus I don't need a seperate viewer. However, I found it is [not straightforward](http://tex.stackexchange.com/questions/2099/how-to-include-svg-diagrams-in-latex) to embed an SVG when using pdf as the output.

[SyncTeX](http://tex.stackexchange.com/questions/118489/what-exactly-is-synctex) as I understand is an editor/IDE feature and not strictly related to TeX itself.

_Minimal context: this endeavor of mine is part of a university course I teach and wanted to show some development experience that feels like 2017. Thank you for the set of macros which greatly facilitate this. As a demo I spun up [VS Code](https://code.visualstudio.com/) with the [CMake](https://marketplace.visualstudio.com/items?itemName=twxs.cmake) and [CMake Tools](https://marketplace.visualstudio.com/items?itemName=vector-of-bool.cmake-tools) extensions for syntax highlight and GUI integration of the build system. Microsofts [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) extension for language services and also Microsofts [LaTeX](https://marketplace.visualstudio.com/items?itemName=ms-vscode.latex) extension for TeX syntax highlight. And the [vscode-pdf](https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf) extension for an integrated PDF viewer based on PDF.js. SyncTeX support is currently missing, plus the PDF does not refresh when the file updates, and there is no GnuPlot syntax highlighting, but these are just a matter of a few feature requests and weeks of patience. :)_

End result:

![2017-03-23](https://cloud.githubusercontent.com/assets/9763499/24287757/32b82d8c-107b-11e7-8e37-1a761d9bb95c.png)
