### ISSUE TITLE
Question: .dot, .svg auto-conversion support?

### ISSUE THREAD

**Issue by eyalroz** [kmorel/UseLATEX#35]
Does UseLATEX support:

* Auto-conversion of .svg to .pdf files (using, say, inkscape)?
* Auto-conversion of .dot to .svg files (using graphviz)?

(I would tag this as a 'question' but I don't have that option.)

**Comment by kmorel** [comment]
> Does UseLATEX support:
> 
> * Auto-conversion of .svg to .pdf files (using, say, inkscape)?

Yes.

> * Auto-conversion of .dot to .svg files (using graphviz)?

No, and it is unlikely it ever will. UseLATEX automatically converts images from one format to another. However, it is outside the scope of UseLATEX to run a program that generates an image based on some specification file. This has come up frequently for generating plots using tools like gnuplot and gri. In the end it is too onerous for UseLATEX to try to support every type of program that is useful for generating images for LaTeX documents. Instead, UseLATEX expects you to create your own CMake targets to create the images and then give `add_latex_document` a dependency on your target.

I am closing this issue. If I have not answered your questions, feel free to re-open it.

**Comment by kmorel** [comment]
One more comment I forgot to mention. The [UseLATEX documentation](https://cmake.org/Wiki/images/d/d7/UseLATEX.pdf) has an example of creating a CMake file that automatically use gri to create a plot and then add that to a LaTeX document (section 6.8). That might be a helpful example in doing something similar with graphviz.
