### ISSUE TITLE
Better default target specification

### ISSUE THREAD

**Issue by kmorel** [kmorel/UseLATEX#5]
Currently, the default target is dvi unless specified with the DEFAULT_PDF or DEFAULT_SAFEPDF option to add_latex_document.  This means that the default is specified per document, but the default build is often more of a preference to users.

At some point, I would like to change the interface to use CMake variables to specify which target gets added to the default.  These CMake variables could be initialized with environment variables or some configure file.

That said, some documents need to be compiled either with latex or pdflatex but not both (although proper use of UseLATEX should remove that).  In that case, you don't really want to set the default but rather force the build to one or the other.  Thus, in addition to these CMake variables, there should be replacement add_latex_document options to support only one LaTeX compiler or the other.

**Comment by zbeekman** [comment]
Sorry I was never able to get to this. I just took a look at the 2.o branch and am _**very**_ excited about it. One of the chief impediments to getting up to speed was a lot of the crazy stuff you were doing to hide variables from the use and to make them global, as well as the argument parsing magic. It seems now that CMake has it’s own argument parsing, borrowed from this project, and now that support for deprecated features is being dropped the code is looking a lot more tractable.

**Comment by kmorel** [comment]
The UseLATEX.cmake 2.0 version is officially released and implements the new target specifications.
