### ISSUE TITLE
Hide LaTeX output unless make is called with VERBOSE=1

### ISSUE THREAD

**Issue by gruenich** [kmorel/UseLATEX#8]
The output of a LaTeX run is verbose and contains a lot of Warnings especially when the references are not known.
I would like to get the output suppressed unless make is called with VERBOSE=1 as it is done for compilation of e.g. C++ files.

**Comment by gruenich** [comment]
I see your concerns and they have point.

What's about the possibility to redirect the output to an log file. The file name is printed out. In case of error we could still load the file and dump it to the terminal.

**Comment by kmorel** [comment]
Christoph, That is pretty much the same suggestion as Izaak's above. It sounds nice, but as I outlined in the last comment there are a lot of very nasty potential consequences.

**Comment by gruenich** [comment]
I guess this is desired, but no way to implement it. Won't fix or deferred for the time being.
